#!/usr/bin/env python3
"""Generate the two per-workspace files for an extra PostHog instance.

Reads the instance variables exported by lib.sh, the resolved compose config of the
workspace, and the slim phrocs config that slim-stack/apply.sh wrote into the workspace.

Writes:
  OVERRIDE_FILE  compose override: unpublish every host port except the proxy, point the
                 proxy's Caddyfile at this instance's host processes, and make Kafka
                 advertise an address the host can reach (OrbStack DNS).
  PROCS_FILE     phrocs config: the slim config with the shells that hardcode ports
                 replaced by instance-aware ones.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import yaml

E = os.environ
WS = Path(E["WS_PATH"])
PROJECT = E["PROJECT"]
ORB = E["ORB"]
OVERRIDE_FILE = Path(E["OVERRIDE_FILE"])
PROCS_FILE = Path(E["PROCS_FILE"])
P = {k: int(E[k]) for k in (
    "BACKEND_PORT", "PROXY_PORT", "VITE_PORT", "FLAGS_PORT", "HYPERCACHE_PORT",
    "EMBEDDING_PORT", "GATEWAY_PORT", "MCP_PORT", "WORKER_METRICS_PORT", "DEBUGPY_PORT",
)}
COMPOSE_FILES = ["-f", "docker-compose.dev.yml", "-f", "docker-compose.profiles.yml"]
PROFILES = ["--profile", "temporal"]
HEADER = "# Generated by posthog_configs/multi-instance/gen_config.py for instance '{}'. Do not edit; re-run build_env.sh.\n"


CH_DEFAULT_SRC = WS / "docker" / "clickhouse" / "config.d" / "default.xml"
CH_DEFAULT_OUT = OVERRIDE_FILE.parent / "clickhouse-default.xml"
CH_ALIAS = f"clickhouse.{ORB}"


def write_clickhouse_config() -> None:
    """Cluster definition with an unambiguous host name.

    The migration runner (and everything else built on posthog.clickhouse.cluster) reads
    host names from system.clusters and connects to them from the Mac. The upstream name is
    the bare `clickhouse`, which /etc/hosts maps to 127.0.0.1, i.e. the main instance's
    published port. The OrbStack name resolves to this instance's container from the Mac,
    and a network alias makes it resolve to the container's own IP inside the network, which
    ClickHouse needs to recognise itself when it executes ON CLUSTER DDL.
    """
    xml = CH_DEFAULT_SRC.read_text()
    if "<host>clickhouse</host>" not in xml:
        raise SystemExit(f"{CH_DEFAULT_SRC} no longer lists <host>clickhouse</host>; update gen_config.py")
    CH_DEFAULT_OUT.parent.mkdir(parents=True, exist_ok=True)
    CH_DEFAULT_OUT.write_text(xml.replace("<host>clickhouse</host>", f"<host>{CH_ALIAS}</host>"))


def compose_config() -> dict:
    env = {k: v for k, v in E.items() if k != "COMPOSE_FILE"}
    cmd = ["docker", "compose", "-p", PROJECT, *COMPOSE_FILES, *PROFILES, "config", "--format", "json"]
    out = subprocess.run(cmd, cwd=WS, check=True, capture_output=True, text=True, env=env)
    return json.loads(out.stdout)


def write_override(cfg: dict) -> None:
    services = cfg["services"]
    lines = [HEADER.format(E["INSTANCE_NAME"]), "services:"]
    for name in sorted(services):
        svc = services[name]
        block: list[str] = []
        if svc.get("ports"):
            if name == "proxy":
                block.append(f'    ports: !override\n      - "127.0.0.1:{P["PROXY_PORT"]}:8000"')
            else:
                block.append("    ports: !reset []")
        if name == "proxy":
            caddy = svc["environment"]["CADDYFILE"]
            for old, new in (
                ("web:8000", f"web:{P['BACKEND_PORT']}"),
                ("feature-flags:3001", f"feature-flags:{P['FLAGS_PORT']}"),
                ("hypercache-server:3002", f"hypercache-server:{P['HYPERCACHE_PORT']}"),
            ):
                if old not in caddy:
                    raise SystemExit(f"proxy Caddyfile no longer contains '{old}'; update gen_config.py")
                caddy = caddy.replace(old, new)
            block.append("    environment:\n      CADDYFILE: |\n" + textwrap.indent(caddy.rstrip("\n"), "        "))
        if name == "clickhouse":
            block.append(f"    networks:\n      default:\n        aliases:\n          - {CH_ALIAS}")
            block.append(f"    volumes:\n      - {CH_DEFAULT_OUT}:/etc/clickhouse-server/config.d/default.xml")
        if name == "kafka":
            cmd = svc.get("command")
            if not isinstance(cmd, list):
                raise SystemExit("kafka service command is not a list; update gen_config.py")
            patched = []
            hit = False
            for item in cmd:
                if item.startswith("--advertise-kafka-addr") and "external://localhost:19092" in item:
                    item = item.replace("external://localhost:19092", f"external://kafka.{ORB}:19092")
                    hit = True
                patched.append(item)
            if not hit:
                raise SystemExit("kafka --advertise-kafka-addr external listener not found; update gen_config.py")
            block.append("    command:\n" + "\n".join(f"      - {json.dumps(i)}" for i in patched))
        if block:
            lines.append(f"  {name}:")
            lines.extend(block)
    OVERRIDE_FILE.parent.mkdir(parents=True, exist_ok=True)
    OVERRIDE_FILE.write_text("\n".join(lines) + "\n")


def rust_shell(binary: str, exports: dict[str, str], pre: str = "") -> str:
    env_part = " ".join(f"{k}={v}" for k, v in exports.items())
    return f"bin/wait-for-docker && {pre}cd rust && exec env {env_part} cargo run --bin {binary}"


def write_procs() -> None:
    src = Path(E["MAIN_REPO"]) / ".posthog" / ".generated" / "mprocs.yaml"
    doc = yaml.safe_load(src.read_text())
    if "ngrok" not in doc["procs"] or doc["procs"].get("celery-worker"):
        print(f"warning: {src} does not look like the slim config; the instance mirrors whatever it is", file=sys.stderr)
    procs = doc["procs"]
    doc.pop("_posthog", None)
    procs.pop("ngrok", None)  # tunnels stay on the main instance

    compose = f"docker compose -p {PROJECT} {' '.join(COMPOSE_FILES)} -f {OVERRIDE_FILE} {' '.join(PROFILES)}"
    procs["docker-compose"]["shell"] = (
        f'{compose} up --pull always -d || {{ echo "docker compose up failed (see the error above)"; exit 1; }} '
        f'&& echo "docker-compose ready" && {compose} logs --tail=100 -f'
    )

    procs["backend"]["shell"] = (
        "bin/wait-for-docker && export PROMETHEUS_MULTIPROC_DIR=$(mktemp -d) && exec python "
        f"-m debugpy --listen 127.0.0.1:{P['DEBUGPY_PORT']} -m granian --interface asgi posthog.asgi:application "
        "--reload --reload-paths ./posthog --reload-paths ./ee --reload-paths ./products "
        f"--reload-paths ./frontend/src/products.json --host 127.0.0.1 --port {P['BACKEND_PORT']} "
        "--log-level debug --workers 1 --workers-kill-timeout 5"
    )

    procs["frontend"]["shell"] = (
        "pnpm --filter=@posthog/frontend... install && bin/turbo run build --filter='@posthog/frontend^...' "
        "&& cd frontend && pnpm build:products && exec pnpm exec concurrently --kill-others-on-fail "
        f'-n VITE,TOOLBAR,WORKERS -c green,magenta,cyan "vite --host 0.0.0.0 --port {P["VITE_PORT"]}" '
        '"pnpm watch:toolbar" "pnpm watch:workers"'
    )

    procs["feature-flags"]["shell"] = rust_shell(
        "feature-flags",
        {
            "RUST_LOG": "debug,tower=warn,maxminddb=warn", "RUST_BACKTRACE": "1",
            "WRITE_DATABASE_URL": '"$DATABASE_URL"', "READ_DATABASE_URL": '"$DATABASE_URL"',
            "MAXMIND_DB_PATH": "../share/GeoLite2-City.mmdb", "REDIS_URL": '"$REDIS_URL"',
            "FLAGS_REDIS_URL": '"$FLAGS_REDIS_URL"', "ADDRESS": f"0.0.0.0:{P['FLAGS_PORT']}", "DEBUG": "1",
            "ALLOW_INTERNAL_IPS": "true", "INTERNAL_REQUEST_TOKEN": '"${INTERNAL_REQUEST_TOKEN:-dev-internal-token}"',
        },
        pre="./bin/download-mmdb && ",
    )
    procs["hypercache-server"]["shell"] = rust_shell(
        "hypercache-server",
        {"RUST_LOG": "debug", "RUST_BACKTRACE": "1", "REDIS_URL": '"$REDIS_URL"',
         "ADDRESS": f"0.0.0.0:{P['HYPERCACHE_PORT']}", "DEBUG": "1"},
    )
    procs["embedding-worker"]["shell"] = rust_shell(
        "embedding-worker",
        {"RUST_LOG": "debug,rdkafka=warn", "RUST_BACKTRACE": "1", "KAFKA_CONSUMER_GROUP": "embedding-worker",
         "KAFKA_CONSUMER_TOPIC": "document_embeddings_input", "FRAME_CACHE_TTL_SECONDS": "1",
         "BIND_PORT": str(P["EMBEDDING_PORT"]), "ALLOW_INTERNAL_IPS": "true",
         "DATABASE_URL": '"$DATABASE_URL"', "KAFKA_HOSTS": '"$KAFKA_HOSTS"'},
    )

    worker = ("python manage.py start_temporal_worker --task-queue development-task-queue "
              "--max-concurrent-workflow-tasks=1000 --max-concurrent-activities=1000")
    procs["temporal-worker"]["shell"] = (
        "bin/wait-for-docker temporal && python manage.py register_temporal_search_attributes && "
        'if [ -n "$TEMPORAL_DISABLE_HOT_RELOAD" ] || ! command -v nodemon >/dev/null 2>&1; then '
        f"{worker}; else nodemon -w common -w dags -w ee -w posthog -w products -w pyproject.toml -e py "
        f'--signal SIGTERM --exec "{worker}"; fi'
    )

    # On a fresh database the Postgres migration runs for minutes, and the ClickHouse
    # migration's own Postgres connection dies mid-way if the two overlap. Upstream only
    # waits for one table to exist; wait for the whole plan instead.
    procs["migrate-clickhouse"]["shell"] = (
        "bin/wait-for-docker && bin/wait-for-postgres-tables posthog_instancesetting && "
        "until python manage.py migrate --check >/dev/null 2>&1; do echo 'waiting for postgres migrations'; sleep 15; done && "
        "bin/migrate --scope=clickhouse"
    )

    gw_env = procs["llm-gateway"].setdefault("env", {})
    gw_env["LLM_GATEWAY_POSTHOG_HOST"] = f"http://localhost:{P['PROXY_PORT']}"
    gw_env["LLM_GATEWAY_PORT"] = str(P["GATEWAY_PORT"])

    procs["mcp"]["shell"] = f"PORT={P['MCP_PORT']} bin/start-mcp-server"

    PROCS_FILE.parent.mkdir(parents=True, exist_ok=True)
    PROCS_FILE.write_text(HEADER.format(E["INSTANCE_NAME"]) + yaml.safe_dump(doc, sort_keys=False, width=4096))


if __name__ == "__main__":
    write_clickhouse_config()
    write_override(compose_config())
    write_procs()
    print(f"wrote {CH_DEFAULT_OUT}\nwrote {OVERRIDE_FILE}\nwrote {PROCS_FILE}")
